import { z } from "zod";
import { defineModule } from "../manifest";

/**
 * The site core: what every site has regardless of kind or pack. Design (themes, pages,
 * navigation, publications, redirects), media, domains, tracking and consent, the site
 * profile with business identity and locations, store settings, members, analytics, the
 * ecosystem (Kârmatik, Yanıt) and developer access. Pages and landings use the content
 * resource, so it belongs here: switching the content module off hides entries, never pages.
 */
export const coreModule = defineModule({
  key: "core",
  version: "1.0.0",
  label: { tr: "Site çekirdeği", en: "Site core" },
  description: {
    tr: "Tema, sayfalar, menüler, medya, alan adları, izleme, işletme kimliği ve lokasyonlar. Her sitede açıktır.",
    en: "Theme, pages, navigation, media, domains, tracking, business identity and locations. Always on.",
  },
  alwaysOn: true,
  dependsOn: [],
  resources: [
    "organization",
    "members",
    "store",
    "settings",
    "site",
    "storefront",
    "content",
    "media",
    "domains",
    "tracking",
    "marketing",
    "analytics",
    "karmatik",
    "yanit",
    "ai_actions",
    "developer",
    "audit",
  ],
  routes: [
    { id: "core.home", path: "/", match: "exact", cacheClass: "public", pageClass: "marketing" },
    { id: "core.pages", path: "/pages", match: "prefix", cacheClass: "public", pageClass: "marketing" },
    { id: "core.search", path: "/search", match: "exact", cacheClass: "public", pageClass: "marketing" },
  ],
  templates: [],
  settings: z.object({}),
  events: [
    "store.created",
    "store.settings_updated",
    "member.invited",
    "domain.activated",
    "domain.routing_changed",
    "domain.status_changed",
    "theme.published",
    "page.published",
    "page.schedule_failed",
    "storefront.publication_switched",
    "redirect.changed",
    "tracking.updated",
    "marketing.consent_changed",
    "asset.uploaded",
    "geo.visibility_changed",
    "profit.margin_breached",
    "ai_action.executed",
    "ekosistem.link_changed",
    "site.profile_changed",
    "site.modules_changed",
    "site.identity_changed",
    "site.locations_changed",
  ],
  adminNav: [
    { key: "home", label: { tr: "Ana sayfa", en: "Home" }, path: "/", permission: "store:read", order: 0 },
    { key: "pages", label: { tr: "Sayfalar", en: "Pages" }, path: "/storefront/pages", permission: "storefront:read", order: 60 },
    { key: "theme", label: { tr: "Tema", en: "Theme" }, path: "/storefront/theme", permission: "storefront:read", order: 61 },
    { key: "navigation", label: { tr: "Menüler", en: "Navigation" }, path: "/storefront/navigation", permission: "storefront:read", order: 62 },
    { key: "media", label: { tr: "Medya", en: "Media" }, path: "/media", permission: "media:read", order: 63 },
    { key: "marketing", label: { tr: "Pazarlama", en: "Marketing" }, path: "/marketing", permission: "marketing:read", order: 70 },
    { key: "analytics", label: { tr: "Analitik", en: "Analytics" }, path: "/analytics", permission: "analytics:read", order: 75 },
    { key: "karmatik", label: { tr: "Kârmatik", en: "Kârmatik" }, path: "/karmatik", permission: "karmatik:read", order: 80 },
    { key: "yanit", label: { tr: "Yanıt", en: "Yanıt" }, path: "/yanit", permission: "yanit:read", order: 81 },
    { key: "site", label: { tr: "Site ve işletme", en: "Site and business" }, path: "/site", permission: "site:read", order: 90 },
    { key: "domains", label: { tr: "Alan adları", en: "Domains" }, path: "/settings/domains", permission: "domains:read", order: 91 },
    { key: "tracking", label: { tr: "İzleme ve çerezler", en: "Tracking and consent" }, path: "/settings/tracking", permission: "tracking:read", order: 92 },
    { key: "settings", label: { tr: "Ayarlar", en: "Settings" }, path: "/settings", permission: "settings:read", order: 95 },
    { key: "members", label: { tr: "Ekip", en: "Team" }, path: "/settings/members", permission: "members:read", order: 96 },
    { key: "developer", label: { tr: "Geliştirici", en: "Developer" }, path: "/settings/developer", permission: "developer:read", order: 97 },
    { key: "audit", label: { tr: "Denetim kaydı", en: "Audit log" }, path: "/settings/audit", permission: "audit:read", order: 98 },
  ],
});
