import { sql } from "drizzle-orm";
import { bigint, boolean, char, index, integer, jsonb, pgEnum, pgTable, text, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { timestamps, tstz } from "./_shared";
import type { EncryptedEnvelope } from "./integrations";
import { pages } from "./storefront";
import { stores } from "./tenancy";

/**
 * Ekosistem v1 bridge (docs/ekosistem/v1.md): per-store links to Kârmatik and Yanıt,
 * one-time link codes, push bookkeeping, tombstones for incremental endpoints, the brand
 * profile altyapi serves, and local read models of what altyapi pulls from its peers.
 * Link secrets are envelope-encrypted and never readable through the API.
 */

export const ekosistemPeerProduct = pgEnum("ekosistem_peer_product", ["karmatik", "yanit"]);
export const ekosistemLinkRole = pgEnum("ekosistem_link_role", ["issuer", "acceptor"]);
export const ekosistemLinkStatus = pgEnum("ekosistem_link_status", ["pending", "awaiting_approval", "active", "revoked"]);
export const ekosistemDeliveryStatus = pgEnum("ekosistem_delivery_status", ["pending", "delivered", "failed"]);
export const ekosistemTombstoneResource = pgEnum("ekosistem_tombstone_resource", ["product", "order", "content"]);

/** Verified identity of the other side as it was shown to the approving user (§4.3). */
export interface EkosistemPeerAccount {
  id: string;
  label: string;
  verifiedDomain: string | null;
  ownerEmailMasked: string | null;
}

/** Retry state of the DELETE {peer}/links/{linkId} notification after a local revoke (§4.4). */
export interface EkosistemRevokeDelivery {
  attempts: number;
  nextAttemptAt: string | null;
  lastError: string | null;
  deliveredAt: string | null;
  /** Retrying stops after 72 hours. */
  giveUpAt: string;
}

export const ekosistemLinks = pgTable(
  "ekosistem_links",
  {
    /** The contract's linkId: generated by altyapi when it issued the code, else by the issuer. */
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid()
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    peerProduct: ekosistemPeerProduct().notNull(),
    /** issuer: altyapi generated the code; acceptor: the user entered a peer's code. */
    role: ekosistemLinkRole().notNull(),
    status: ekosistemLinkStatus().notNull().default("pending"),
    /** Current shared secret (43 base64url characters), envelope-encrypted. */
    secret: jsonb().$type<EncryptedEnvelope>().notNull(),
    /** Secret before the last rotation, accepted until previousSecretValidUntil (24 h). */
    previousSecret: jsonb().$type<EncryptedEnvelope>(),
    previousSecretValidUntil: tstz(),
    /** SHA-256 of the nonce of the last rotate call, so a repeated call returns the same secret. */
    rotateNonceHash: text(),
    rotatedAt: tstz(),
    /** What the peer may read from altyapi. */
    grantedScopes: text().array().notNull().default(sql`ARRAY[]::text[]`),
    /** What altyapi may read from the peer. */
    peerScopes: text().array().notNull().default(sql`ARRAY[]::text[]`),
    peerAccount: jsonb().$type<EkosistemPeerAccount>().notNull(),
    /** SHA-256 of the claimNonce; a repeated claim with the same nonce gets the same answer. */
    claimNonceHash: text(),
    /** pending / awaiting_approval links are removed after this instant (10 minutes). */
    pendingExpiresAt: tstz(),
    createdByUserId: uuid(),
    approvedByUserId: uuid(),
    approvedAt: tstz(),
    revokedAt: tstz(),
    /** user, revoked_by_peer, store_deleted, peer_unverified, ... */
    revokeReason: text(),
    revokeDelivery: jsonb().$type<EkosistemRevokeDelivery>(),
    /** Per-endpoint pull state, e.g. { "profit/variants": { since, cursor } }. */
    cursors: jsonb().$type<Record<string, unknown>>().notNull().default({}),
    lastPullAt: tstz(),
    /**
     * When the scheduled puller should look at this link again (each resource at most
     * hourly); null = due now. The scheduler leases due links by moving this forward.
     */
    nextPullAt: tstz(),
    lastError: text(),
    /** link_invalid answers in a row, counted at least 10 minutes apart (§4.4). */
    consecutiveLinkInvalid: integer().notNull().default(0),
    lastLinkInvalidAt: tstz(),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("ekosistem_links_store_peer_uq").on(t.storeId, t.peerProduct).where(sql`${t.status} <> 'revoked'`),
    index("ekosistem_links_pending_idx").on(t.pendingExpiresAt).where(sql`${t.status} in ('pending', 'awaiting_approval')`),
    index("ekosistem_links_active_idx").on(t.status, t.lastPullAt),
    index("ekosistem_links_due_idx").on(t.nextPullAt).where(sql`${t.status} = 'active'`),
    index("ekosistem_links_store_idx").on(t.storeId, t.createdAt),
  ],
);

/** One-time link codes altyapi issued (§4.2); only the SHA-256 of the normalised code is kept. */
export const ekosistemCodes = pgTable(
  "ekosistem_codes",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid()
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    /** The product the code may be claimed by. */
    peerProduct: ekosistemPeerProduct().notNull(),
    codeHash: text().notNull(),
    /** Scopes the issuing user chose to grant the peer (a narrowing of the §3 defaults). */
    grants: text().array().notNull().default(sql`ARRAY[]::text[]`),
    expiresAt: tstz().notNull(),
    usedAt: tstz(),
    claimNonceHash: text(),
    linkId: uuid().references(() => ekosistemLinks.id, { onDelete: "set null" }),
    createdByUserId: uuid(),
    ...timestamps,
  },
  (t) => [uniqueIndex("ekosistem_codes_hash_uq").on(t.codeHash), index("ekosistem_codes_store_idx").on(t.storeId, t.createdAt)],
);

/** Push events received from peers (§10): idempotency by event id per link. */
export const ekosistemEventReceipts = pgTable(
  "ekosistem_event_receipts",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    eventId: uuid().notNull(),
    type: text().notNull(),
    ref: text(),
    occurredAt: tstz(),
    receivedAt: tstz().notNull().defaultNow(),
    /** When the pull triggered by this event ran (pulls for the same type/ref are coalesced). */
    processedAt: tstz(),
  },
  (t) => [
    uniqueIndex("ekosistem_event_receipts_uq").on(t.linkId, t.eventId),
    index("ekosistem_event_receipts_pending_idx").on(t.linkId, t.type, t.ref).where(sql`${t.processedAt} is null`),
    index("ekosistem_event_receipts_received_idx").on(t.receivedAt),
  ],
);

/** Push events altyapi sends to peers (§10): at most 5 attempts with exponential backoff. */
export const ekosistemDeliveries = pgTable(
  "ekosistem_deliveries",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    /** The push `id` sent to the peer. */
    eventId: uuid().notNull(),
    type: text().notNull(),
    ref: text().notNull(),
    occurredAt: tstz().notNull(),
    status: ekosistemDeliveryStatus().notNull().default("pending"),
    attempts: integer().notNull().default(0),
    nextAttemptAt: tstz().notNull().defaultNow(),
    /**
     * Set when a sender leases the row. A row that was never leased is still collecting
     * changes: further events for the same (link, type, ref) ride along with it (30 s).
     */
    leasedUntil: tstz(),
    lastError: text(),
    deliveredAt: tstz(),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("ekosistem_deliveries_uq").on(t.linkId, t.eventId),
    index("ekosistem_deliveries_due_idx").on(t.nextAttemptAt).where(sql`${t.status} = 'pending'`),
    // Coalescing (§10): at most one not-yet-sent push per (link, type, ref).
    uniqueIndex("ekosistem_deliveries_coalesce_uq")
      .on(t.linkId, t.type, t.ref)
      .where(sql`${t.status} = 'pending' and ${t.attempts} = 0 and ${t.leasedUntil} is null`),
    index("ekosistem_deliveries_finished_idx").on(t.updatedAt).where(sql`${t.status} <> 'pending'`),
  ],
);

/**
 * Deleted records for incremental endpoints (§6.3): returned as { ref, deleted: true,
 * updatedAt } to consumers asking with `since`. Kept 30 days (orders 90 days).
 */
export const ekosistemTombstones = pgTable(
  "ekosistem_tombstones",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid()
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    resource: ekosistemTombstoneResource().notNull(),
    ref: text().notNull(),
    deletedAt: tstz().notNull().defaultNow(),
  },
  (t) => [uniqueIndex("ekosistem_tombstones_uq").on(t.storeId, t.resource, t.ref), index("ekosistem_tombstones_since_idx").on(t.storeId, t.resource, t.deletedAt)],
);

export interface BrandCompetitor {
  name: string;
  website: string | null;
  aliases: string[];
}

/** Brand identity served as GET /ekosistem/v1/brand (§7.1); edited by the merchant. */
export const storeBrandProfiles = pgTable("store_brand_profiles", {
  storeId: uuid()
    .primaryKey()
    .references(() => stores.id, { onDelete: "cascade" }),
  organizationId: uuid().notNull(),
  description: text(),
  topics: text().array().notNull().default(sql`ARRAY[]::text[]`),
  competitors: jsonb().$type<BrandCompetitor[]>().notNull().default([]),
  socialProfiles: text().array().notNull().default(sql`ARRAY[]::text[]`),
  updatedByUserId: uuid(),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// Kârmatik read models (§8). Amounts are minor units; each row keeps the validated payload.
// ---------------------------------------------------------------------------

/** §8.2 profitability per variant/channel (profit:read, or profit:summary with summaryOnly). */
export const karmatikProfitSnapshots = pgTable(
  "karmatik_profit_snapshots",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    ref: text().notNull(),
    sourceRef: text(),
    /** Local variant matched by sourceRef → barcode → sku (§6.2). */
    variantId: uuid(),
    channel: text(),
    storeLabel: text(),
    barcode: text(),
    sku: text(),
    currency: char({ length: 3 }),
    price: bigint({ mode: "bigint" }),
    netProfit: bigint({ mode: "bigint" }),
    marginBps: integer(),
    floorPrice: bigint({ mode: "bigint" }),
    floorBasis: text(),
    minMarginBps: integer(),
    safeDiscountBps: integer(),
    breakEvenPrice: bigint({ mode: "bigint" }),
    lossMaking: boolean(),
    /** estimated | realized */
    basis: text(),
    missing: text().array().notNull().default(sql`ARRAY[]::text[]`),
    /** True when read with profit:summary only (ref, marginBps, lossMaking). */
    summaryOnly: boolean().notNull().default(false),
    peerUpdatedAt: tstz().notNull(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("karmatik_profit_snapshots_uq").on(t.linkId, t.ref),
    index("karmatik_profit_snapshots_variant_idx").on(t.storeId, t.variantId),
    index("karmatik_profit_snapshots_source_idx").on(t.storeId, t.sourceRef),
  ],
);

export const karmatikSuggestionLocalStatus = pgEnum("karmatik_suggestion_local_status", ["new", "applied", "dismissed"]);

/** §8.3 price suggestions and the merchant's decision, delivered back with pricing:decide. */
export const karmatikPriceSuggestions = pgTable(
  "karmatik_price_suggestions",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    ref: text().notNull(),
    sourceRef: text(),
    variantId: uuid(),
    channel: text().notNull(),
    barcode: text(),
    currency: char({ length: 3 }).notNull(),
    currentPrice: bigint({ mode: "bigint" }).notNull(),
    suggestedPrice: bigint({ mode: "bigint" }).notNull(),
    reason: text().notNull(),
    competitorMinPrice: bigint({ mode: "bigint" }),
    /** Confidence 0..1 as basis points; null when Kârmatik gives none. */
    confidenceBps: integer(),
    /** open | applied | dismissed, as Kârmatik reports it. */
    peerStatus: text().notNull(),
    peerCreatedAt: tstz().notNull(),
    peerUpdatedAt: tstz().notNull(),
    localStatus: karmatikSuggestionLocalStatus().notNull().default("new"),
    decidedByUserId: uuid(),
    decidedAt: tstz(),
    /** Idempotency id of the decision sent to Kârmatik. */
    decisionId: uuid(),
    decisionAppliedPrice: bigint({ mode: "bigint" }),
    decisionDeliveryStatus: ekosistemDeliveryStatus(),
    decisionAttempts: integer().notNull().default(0),
    decisionNextAttemptAt: tstz(),
    decisionLastError: text(),
    decisionDeliveredAt: tstz(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("karmatik_price_suggestions_uq").on(t.linkId, t.ref),
    index("karmatik_price_suggestions_store_idx").on(t.storeId, t.localStatus, t.peerUpdatedAt),
    index("karmatik_price_suggestions_decision_due_idx").on(t.decisionNextAttemptAt).where(sql`${t.decisionDeliveryStatus} = 'pending'`),
  ],
);

/** §8.5 alerts. */
export const karmatikAlerts = pgTable(
  "karmatik_alerts",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    ref: text().notNull(),
    channel: text().notNull(),
    storeLabel: text(),
    type: text().notNull(),
    severity: text().notNull(),
    barcode: text(),
    sourceRef: text(),
    variantId: uuid(),
    title: text().notNull(),
    body: text().notNull(),
    currency: char({ length: 3 }),
    impactMonthly: bigint({ mode: "bigint" }),
    peerCreatedAt: tstz().notNull(),
    peerUpdatedAt: tstz().notNull(),
    resolvedAt: tstz(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    ...timestamps,
  },
  (t) => [uniqueIndex("karmatik_alerts_uq").on(t.linkId, t.ref), index("karmatik_alerts_store_idx").on(t.storeId, t.resolvedAt, t.peerUpdatedAt)],
);

/** §8.4 current competitor offers (a disappearing offer arrives as a tombstone). */
export const karmatikCompetitorPrices = pgTable(
  "karmatik_competitor_prices",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    ref: text().notNull(),
    sourceRef: text(),
    barcode: text(),
    variantId: uuid(),
    source: text().notNull(),
    seller: text(),
    currency: char({ length: 3 }).notNull(),
    price: bigint({ mode: "bigint" }).notNull(),
    url: text(),
    inStock: boolean(),
    observedAt: tstz().notNull(),
    peerUpdatedAt: tstz().notNull(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    ...timestamps,
  },
  (t) => [uniqueIndex("karmatik_competitor_prices_uq").on(t.linkId, t.ref), index("karmatik_competitor_prices_variant_idx").on(t.storeId, t.variantId)],
);

// ---------------------------------------------------------------------------
// Yanıt read models (§9)
// ---------------------------------------------------------------------------

/** §9.1 visibility summary, one history row per pulled snapshot (compared to find changes). */
export const yanitVisibilitySnapshots = pgTable(
  "yanit_visibility_snapshots",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    windowDays: integer().notNull(),
    validRuns: integer().notNull(),
    runsWithBrand: integer().notNull(),
    visibilityBps: integer(),
    shareOfVoiceBps: integer(),
    previousBps: integer(),
    deltaBps: integer(),
    lastMeasuredAt: tstz(),
    asOf: tstz().notNull(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    createdAt: tstz().notNull().defaultNow(),
  },
  (t) => [uniqueIndex("yanit_visibility_snapshots_uq").on(t.linkId, t.windowDays, t.asOf), index("yanit_visibility_snapshots_store_idx").on(t.storeId, t.windowDays, t.asOf)],
);

/** §9.2 missing queries (snapshot, replaced on every pull). */
export const yanitGaps = pgTable(
  "yanit_gaps",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    ref: text().notNull(),
    query: text().notNull(),
    providers: text().array().notNull().default(sql`ARRAY[]::text[]`),
    competitorsMentioned: text().array().notNull().default(sql`ARRAY[]::text[]`),
    priority: integer().notNull(),
    intent: text(),
    lastRunAt: tstz(),
    asOf: tstz().notNull(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    ...timestamps,
  },
  (t) => [uniqueIndex("yanit_gaps_uq").on(t.linkId, t.ref), index("yanit_gaps_store_idx").on(t.storeId, t.priority)],
);

export const yanitOpportunityLocalStatus = pgEnum("yanit_opportunity_local_status", ["new", "drafted", "dismissed"]);

/** §9.3 content opportunities; a merchant-approved draft page may be created (never auto-published). */
export const yanitOpportunities = pgTable(
  "yanit_opportunities",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    ref: text().notNull(),
    kind: text().notNull(),
    sourceKind: text(),
    title: text().notNull(),
    body: text().notNull(),
    query: text(),
    targetUrl: text(),
    impact: text().notNull(),
    /** open | done | dismissed, as Yanıt reports it. */
    peerStatus: text().notNull(),
    peerCreatedAt: tstz().notNull(),
    peerUpdatedAt: tstz().notNull(),
    localStatus: yanitOpportunityLocalStatus().notNull().default("new"),
    draftPageId: uuid().references(() => pages.id, { onDelete: "set null" }),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    ...timestamps,
  },
  (t) => [uniqueIndex("yanit_opportunities_uq").on(t.linkId, t.ref), index("yanit_opportunities_store_idx").on(t.storeId, t.localStatus, t.peerUpdatedAt)],
);

/** §9.4 cited sources (snapshot per window, replaced on every pull). */
export const yanitCitations = pgTable(
  "yanit_citations",
  {
    id: uuid().primaryKey(),
    organizationId: uuid().notNull(),
    storeId: uuid().notNull(),
    linkId: uuid()
      .notNull()
      .references(() => ekosistemLinks.id, { onDelete: "cascade" }),
    windowDays: integer().notNull(),
    domain: text().notNull(),
    count: integer().notNull(),
    shareBps: integer(),
    sampleUrls: text().array().notNull().default(sql`ARRAY[]::text[]`),
    asOf: tstz().notNull(),
    ...timestamps,
  },
  (t) => [uniqueIndex("yanit_citations_uq").on(t.linkId, t.windowDays, t.domain), index("yanit_citations_store_idx").on(t.storeId, t.windowDays, t.count)],
);
