import { createHash, randomBytes } from "node:crypto";
import type { EkosistemProduct } from "./constants";

/**
 * Link codes (§4.2): `ek1_<issuer>_<26 Crockford base32>`, 130 random bits, valid for
 * 10 minutes, single use. Only the SHA-256 of the normalised code is stored.
 */

const CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const CODE_BODY_LENGTH = 26;

export const ISSUER_LETTER: Record<EkosistemProduct, "a" | "k" | "y"> = { altyapi: "a", karmatik: "k", yanit: "y" };
const PRODUCT_BY_LETTER: Record<string, EkosistemProduct> = { A: "altyapi", K: "karmatik", Y: "yanit" };

const NORMALIZED_RE = /^EK1_([AKY])_([0-9A-HJKMNP-TV-Z]{26})$/;

/** 26 Crockford base32 characters (130 bits) from 17 random bytes; each 5-bit group is uniform. */
function randomCrockford(length: number): string {
  const bytes = randomBytes(Math.ceil((length * 5) / 8));
  let out = "";
  let acc = 0;
  let bits = 0;
  let i = 0;
  while (out.length < length) {
    if (bits < 5) {
      acc = (acc << 8) | bytes[i++]!;
      bits += 8;
    }
    bits -= 5;
    out += CROCKFORD[(acc >> bits) & 31];
    acc &= (1 << bits) - 1;
  }
  return out;
}

/** A fresh code issued by `issuer` (altyapi issues `ek1_a_…`). */
export function generateEkosistemCode(issuer: EkosistemProduct = "altyapi"): string {
  return `ek1_${ISSUER_LETTER[issuer]}_${randomCrockford(CODE_BODY_LENGTH)}`;
}

/**
 * Normalisation before hashing (§4.2): upper-case, drop whitespace and "-", then
 * O→0, I→1, L→1 so codes read aloud or typed by hand still match.
 */
export function normalizeEkosistemCode(input: string): string {
  return input.toUpperCase().replace(/[\s-]+/g, "").replace(/O/g, "0").replace(/[IL]/g, "1");
}

export interface ParsedEkosistemCode {
  issuer: EkosistemProduct;
  normalized: string;
  hash: string;
}

/** Parses a user-entered code; null when it cannot be a v1 code. */
export function parseEkosistemCode(input: string): ParsedEkosistemCode | null {
  if (typeof input !== "string" || input.length > 100) return null;
  const normalized = normalizeEkosistemCode(input);
  const m = NORMALIZED_RE.exec(normalized);
  if (!m) return null;
  return { issuer: PRODUCT_BY_LETTER[m[1]!]!, normalized, hash: sha256(normalized) };
}

/** SHA-256 (hex) of the normalised code; the only form that is stored. */
export function hashEkosistemCode(input: string): string {
  return sha256(normalizeEkosistemCode(input));
}

/** Codes never reach logs; this keeps only the version and issuer for diagnostics. */
export function redactEkosistemCode(input: string): string {
  const parsed = parseEkosistemCode(input);
  return parsed ? `ek1_${ISSUER_LETTER[parsed.issuer]}_[redacted]` : "[redacted]";
}

/** claimNonce: 32 random bytes as base64url (43 characters), generated by the acceptor. */
export function generateClaimNonce(): string {
  return randomBytes(32).toString("base64url");
}

export function hashClaimNonce(nonce: string): string {
  return sha256(nonce);
}

function sha256(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}
